version: '3'
services:
  # nginx:
  #   depends_on:
  #     - api
  #     - client
  #   restart: always
  #   build: 
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #       - "80:80"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - "5432:5432"  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  # api:
  #   depends_on:
  #     - postgres
  #     - redis
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   volumes:
  #      - /app/node_modules
  #      - ./server:/app  
  #   environment:
  #     - PORT=4000
  #     - REDIS_HOST=redis
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
  #   ports:
  #     - "4000:4000"  
  # client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   volumes:
  #      - /app/node_modules
  #      - ./client:/app
  # worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes:
  #      - /app/node_modules
  #      - ./worker:/app
  #   environment:
  #     - REDIS_HOST=redis
        