version: '3'

services:
 zookeeper:
  image: 'bitnami/zookeeper:latest'
  container_name: zookeeper
  environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     ALLOW_ANONYMOUS_LOGIN: "yes"  
 kafka:
  image: 'bitnami/kafka:latest'
  container_name: broker
  environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,state.change.logger=ERROR"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
  depends_on:
     - zookeeper
 mongo: 
   image: 'mongo:latest'
   container_name: mongo  
 producer:
  build: ./server
  container_name: 'producer'
  ports:
      - '3000:3000'
  environment:
   - PORT=3000
   - KAFKA_HOST=broker
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_BROKER_ID=1
   - KAFKA_CLIENT_ID=producer
   - MONGODB_URI=mongodb://mongo:27017/complex
  depends_on:
    - broker
    - mongo             
 consumer:
  build: ./worker
  container_name: 'consumer'
  environment:
   - PORT=3001
   - KAFKA_HOST=broker
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_CLIENT_ID=consumer
   - KAFKA_GROUP_ID=consumer
   - SIGNING_SECRET=${SIGNING_SECRET}
   - BOT_TOKEN=${BOT_TOKEN}
   - MONGODB_URI=mongodb://mongo:27017/complex
  depends_on:
    - broker
    - mongo

     