version: '3'
services:
 zookeeper:
  image: 'bitnami/zookeeper:latest'
  container_name: 'zookeeper'
  environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 kafka:
  image: 'bitnami/kafka:latest'
  container_name: 'kafka'
  ports:
      - '9092:9092'
  environment:
        KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  depends_on:
      - zookeeper
 producer:
  build: ./server
  container_name: 'producer'
  ports:
      - '3000:3000'
  environment:
   - PORT: 3000
   - KAFKA_HOST=kafka
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_BROKER_ID=1
   - KAFKA_CLIENT_ID=producer
  depends_on:
      - kafka               
 consumer:
  build: ./worker
  container_name: 'consumer'
  ports:
      - '3001:3001'
  environment:
   - PORT=3001
   - KAFKA_HOST=kafka
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_GROUP_ID=worker
   - KAFKA_BROKER_ID=2
   - KAFKA_CLIENT_ID=consumer
  depends_on:
      - kafka 