version: '3'

services:
 zookeeper:
  image: 'bitnami/zookeeper:latest'
  container_name: zookeeper
  environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     ALLOW_ANONYMOUS_LOGIN: "yes"
 zookeeper2:
  image: 'bitnami/zookeeper:latest'
  container_name: zookeeper2
  environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     ALLOW_ANONYMOUS_LOGIN: "yes"
 zookeeper3:
   image: 'bitnami/zookeeper:latest'
   container_name: zookeeper3
   environment:
     ALLOW_PLAINTEXT_LISTENER: "yes"
     ALLOW_ANONYMOUS_LOGIN: "yes"      
 kafka:
  image: 'bitnami/kafka:latest'
  container_name: broker
  environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
  depends_on:
     - zookeeper
     - zookeeper2
     - zookeeper3   
 kafka2:
   image: 'bitnami/kafka:latest'
   container_name: broker2
   environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
   depends_on:
     - zookeeper
     - zookeeper2
     - zookeeper3
 kafka3:
   image: 'bitnami/kafka:latest'
   container_name: broker3
   environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
   depends_on:
     - zookeeper
     - zookeeper2
     - zookeeper3   
 producer:
  build: ./server
  container_name: 'producer'
  ports:
      - '3000:3000'
  environment:
   - PORT=3000
   - KAFKA_HOST=broker
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_BROKER_ID=1
   - KAFKA_CLIENT_ID=producer
  depends_on:
    - broker
    - broker2
    - broker3               
 consumer:
  build: ./worker
  container_name: 'consumer'
  environment:
   - PORT=3001
   - KAFKA_HOST=broker
   - KAFKA_PORT=9092
   - KAFKA_TOPIC=message
   - KAFKA_CLIENT_ID=consumer
   - KAFKA_GROUP_ID=consumer
   - SIGNING_SECRET=${SIGNING_SECRET}
   - BOT_TOKEN=${BOT_TOKEN}
  depends_on:
    - broker
    - broker2
    - broker3

     